Feature/products
lizavetion/group10_icecream pull request #10
Opened 2023-01-23 10:53 UTC by MartaNazarkevych

2023-01-23 21:54 UTC, lizavetion requested changes

2023-01-23 21:54 UTC, lizavetion commented on src/partials/products.html
> +        <p class="products-sub-tittle">100% NATURAL</p>
"100% natural" має бути прописано через тег label

2023-01-23 21:54 UTC, lizavetion commented on src/partials/products.html
> +                  <img
Згідно ТЗ картинки мають бути прописані через псевдоелементи

2023-01-23 21:54 UTC, lizavetion commented on src/partials/products.html
> +<body>
Не потрібен тег body

2023-01-24 13:38 UTC, MartaNazarkevych commented on src/partials/products.html
> +                  <img
Виправила)

2023-01-24 13:38 UTC, MartaNazarkevych commented on src/partials/products.html
> +<body>
Забрала)

2023-01-24 14:38 UTC, lizavetion approved these changes

2023-01-24 19:57 UTC, merged