updateContacts
lizavetion/group10_icecream pull request #5
Opened 2023-01-22 14:14 UTC by ANDRnewHuman

2023-01-22 21:38 UTC, lizavetion requested changes

2023-01-22 21:38 UTC, lizavetion commented on src/partials/contacts.html
> +        <ul class="contacts-ul list">
Не можу закинути до css ревью, але у contacts-ul має бути медіаправило, що ми обговорювали (щоб список не приклеювався до лівої сторони)

2023-01-24 03:20 UTC, Lyuobomyr requested changes
додай ще відстань між button щоб при 480 і <   кнопка ставала одна під одну

2023-01-24 19:47 UTC, lizavetion approved these changes

2023-01-24 20:14 UTC, merged