feature/modal-video
lizavetion/group10_icecream pull request #7
Opened 2023-01-22 19:01 UTC by KozhaVitalii

Added modal "how it's made" and settings needed for this

2023-01-22 22:00 UTC, lizavetion requested changes

2023-01-23 18:58 UTC, KozhaVitalii commented on src/sass/index.css
> +@import '~node_modules/modern-normalize/modern-normalize.css';
Так, цей файл створив компілятор. Відключу його при оновлені.

2023-01-23 19:07 UTC, KozhaVitalii commented on src/partials/modal-video.html
> + width="1349" height="488" src="https://www.youtube.com/embed/8WEMZ86Eho8"
То я ж тут начеб то у ролі розробника, не плутати з дизайнером :) Якщо є якісь конкретні побажання, надсилай лінк до відео, яке вважаєш більш естетичним, я додам в код. Але як на мене, це останнє на чому зараз потрібно концентрувати увагу, поміняти лінк це 1/2 сек ;)

2023-01-24 19:53 UTC, lizavetion approved these changes

2023-01-24 19:54 UTC, merged